src/main/java/com/stockleague/backend/admin/controller/AdminController.java
src/main/java/com/stockleague/backend/admin/dto/request/AdminUserForceWithdrawRequestDto.java
src/main/java/com/stockleague/backend/admin/dto/response/AdminUserForceWithdrawResponseDto.java
src/main/java/com/stockleague/backend/admin/service/AdminService.java
src/main/java/com/stockleague/backend/auth/controller/AuthController.java
src/main/java/com/stockleague/backend/global/config/SecurityConfig.java
src/main/java/com/stockleague/backend/global/exception/GlobalErrorCode.java
src/main/java/com/stockleague/backend/global/handler/CustomAccessDeniedHandler.java
src/main/java/com/stockleague/backend/user/controller/UserController.java
src/main/java/com/stockleague/backend/user/dto/request/UserWithdrawRequestDto.java
src/main/java/com/stockleague/backend/user/dto/response/UserWithdrawResponseDto.java
src/main/java/com/stockleague/backend/user/service/UserService.java

1. 회원 탈퇴 기능
2. 관리자 회원 강제 탈퇴 기능

feat: 회원 탈퇴 기능 로직 구현

---

src/app/help/inquiry/inquiry.css
src/app/help/inquiry/page.tsx
src/app/help/notice/[id]/noticeDetailPage.css
src/app/help/notice/[id]/page.tsx
src/app/help/notice/notice.css
src/app/help/notice/page.tsx

각각의 페이지 별 UI 및 공지사항, 문의사항 목록 페이징 처리

feat: 공지사항, 문의, 이용안내 페이지 UI 구현

---

src/app/components/DropdownMenu.tsx
src/app/components/StockItem.tsx
src/app/page.tsx
src/app/stocks/stockList/page.tsx
src/app/stocks/stockList/stockList.css
src/app/styles/components/StockItem.module.css
src/app/styles/page.module.css

간단한 카테고리 및 목록을 20개씩 보여주는 UI를 구현

feat: 주식목록페이지 및 메인페이지 주식목록 UI 구현

---

src/app/components/Header.tsx
src/app/components/StockItem.tsx
src/app/page.tsx
src/app/user/account/page.tsx

/component/StockItem 등락률 오류 수정

fix: stockList의 stockItem 오류 수정

---

src/app/components/OrderHistoryItem.tsx
src/app/help/guide/guide.css
src/app/help/help.css
src/app/help/inquiry/inquiry.css
src/app/help/layout.tsx
src/app/help/notice/notice.css
src/app/help/notice/page.tsx
src/app/stocks/stockList/page.tsx
src/app/stocks/stockList/stockList.css
src/app/styles/components/OrderHistoryItem.module.css
src/app/user/account-settings/account-settings.css
src/app/user/account-settings/page.tsx
src/app/user/account/account.css
src/app/user/account/page.tsx
src/app/user/order-history/order-history.css
src/app/user/order-history/page.tsx
src/app/user/user.css

feat: 유저페이지 내계좌, 주문내역, 계정관리 UI 구현

---

src/app/rank/page.tsx
src/app/rank/rank.css

feat: 랭킹페이지 UI 구현

---

src/app/components/Community.tsx
src/app/styles/components/Community.module.css

feat: 커뮤니티 UI 및 페이징 구현

---

src/main/java/com/stockleague/backend/global/config/SecurityConfig.java
src/main/java/com/stockleague/backend/global/exception/GlobalErrorCode.java
src/main/java/com/stockleague/backend/notice/controller/NoticeAdminController.java
src/main/java/com/stockleague/backend/notice/controller/NoticeController.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeSearchResponseDto.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeSummaryDto.java
src/main/java/com/stockleague/backend/notice/repository/NoticeRepository.java
src/main/java/com/stockleague/backend/notice/service/NoticeService.java

1. 검색 기능 구현
2. SecurityConfig에서 공지사항을 권한없이 볼 수 있도록 수정
3. Swagger 문서화를 위한 Tag 수정

feat: 공지사항 검색 기능 구현

---

src/main/java/com/stockleague/backend/global/exception/GlobalErrorCode.java
src/main/java/com/stockleague/backend/notice/controller/NoticeAdminController.java
src/main/java/com/stockleague/backend/notice/controller/NoticeController.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeAdminPageResponseDto.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeAdminSummaryDto.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticePageResponseDto.java
src/main/java/com/stockleague/backend/notice/repository/NoticeRepository.java
src/main/java/com/stockleague/backend/notice/service/NoticeService.java

1. 유저용 공지사항 목록 조회 기능 구현
2. 관리자용 공지사항 목록 조회 기능 구현
3. NoticeSearchResponseDto를 NoticePageResponseDto로 이름 수정

feat: 공지사항 목록 조회 기능 구현

---

src/app/components/InquiryDropdown.tsx

components에 있는 tsx파일 선언식(Function Declaration)에서 표현식 (Function Expression) + Arrow Function 으로 수정

fix: help-page 관련 components 코드 구조 변경

---

src/main/java/com/stockleague/backend/global/exception/GlobalErrorCode.java
src/main/java/com/stockleague/backend/inquiry/controller/InquiryController.java
src/main/java/com/stockleague/backend/inquiry/domain/Inquiry.java
src/main/java/com/stockleague/backend/inquiry/domain/InquiryStatus.java
src/main/java/com/stockleague/backend/inquiry/dto/request/InquiryCreateRequestDto.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryCreateResponseDto.java
src/main/java/com/stockleague/backend/inquiry/repository/InquiryRepository.java
src/main/java/com/stockleague/backend/inquiry/service/InquiryService.java

1. 공지사항의 미사용중인 패키지 import 삭제
2. 문의 작성 기능 구현

feat: 문의 작성 기능 구현

---

src/app/components/TabMenu.tsx

fix: main-page components 구조 수정

---

src/app/auth/terms/page.tsx
src/app/auth/terms/terms.css
src/app/components/NextButton.tsx

선언식 -> 표현식 수정 / 약관동의 페이지 체크박스 추가(만 14세 이상 동의)

fix: login-page components 구조 수정 및 약관동의 수정

---

src/main/java/com/stockleague/backend/global/exception/GlobalErrorCode.java
src/main/java/com/stockleague/backend/inquiry/controller/InquiryAdminController.java
src/main/java/com/stockleague/backend/inquiry/controller/InquiryController.java
src/main/java/com/stockleague/backend/inquiry/domain/InquiryStatus.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryPageResponseDto.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquirySummaryDto.java
src/main/java/com/stockleague/backend/inquiry/repository/InquiryRepository.java
src/main/java/com/stockleague/backend/inquiry/service/InquiryService.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeAdminSummaryDto.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeDetailResponseDto.java
src/main/java/com/stockleague/backend/notice/dto/response/NoticeSummaryDto.java

1. 사용자 문의 목록 조회 기능 구현
2. 관리자용 문의 목록 조회 기능 구현
3. 문의 상태별 필터링 오류 수정 ( status 오입력시 발생 오류 처리 )

feat: 문의 목록 조회 기능 구현

---

src/app/components/MovingAverageSelector.tsx
src/app/components/StockChart.tsx
src/app/components/TimeIntervalSelector.tsx
src/app/styles/components/StockChart.module.css

시간 별 그래프 변화 구현 못 함. 평균 이동 선그래프 단기, 중기, 장기 버튼 연동 안됨.

feat: 그래프 라이브러리 react-lightweight-chart로 변경 및 그래프 UI 구현

---

src/main/java/com/stockleague/backend/inquiry/controller/InquiryAdminController.java
src/main/java/com/stockleague/backend/inquiry/controller/InquiryController.java
src/main/java/com/stockleague/backend/inquiry/domain/InquiryAnswer.java
src/main/java/com/stockleague/backend/inquiry/domain/InquiryStatus.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryAnswerDto.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryDetailForAdminResponseDto.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryDetailForUserResponseDto.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquirySummaryDto.java
src/main/java/com/stockleague/backend/inquiry/repository/InquiryAnswerRepository.java
src/main/java/com/stockleague/backend/inquiry/repository/InquiryRepository.java
src/main/java/com/stockleague/backend/inquiry/service/InquiryService.java
src/main/java/com/stockleague/backend/notice/controller/NoticeAdminController.java

1. 관리자용 문의 상세 정보 조회 기능 구현
2. 유저용 문의 상세 정보 조회 기능 구현
3. 응답에 수정 시각 필드 추가

feat: 문의 상세 정보 조회 기능 구현

---

src/main/java/com/stockleague/backend/global/exception/GlobalErrorCode.java
src/main/java/com/stockleague/backend/inquiry/controller/InquiryAdminController.java
src/main/java/com/stockleague/backend/inquiry/controller/InquiryController.java
src/main/java/com/stockleague/backend/inquiry/domain/Inquiry.java
src/main/java/com/stockleague/backend/inquiry/dto/request/InquiryAnswerCreateRequestDto.java
src/main/java/com/stockleague/backend/inquiry/dto/request/InquiryCreateRequestDto.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryAnswerCreateResponseDto.java
src/main/java/com/stockleague/backend/inquiry/repository/InquiryAnswerRepository.java
src/main/java/com/stockleague/backend/inquiry/service/InquiryAnswerService.java
src/main/java/com/stockleague/backend/inquiry/service/InquiryService.java
src/main/java/com/stockleague/backend/notice/controller/NoticeAdminController.java

1. 문의 답변 기능 구현
2. 필수 기입 내용 미기입시 오류 내용 "내용을 모두 입력해야 합니다."로 수정

feat: 문의 답변 기능 구현

---

src/app/components/MovingAverageSelector.tsx
src/app/components/StockChart.tsx
src/app/components/TimeIntervalSelector.tsx
src/app/styles/components/StockChart.module.css

단기 5일, 중기 20일, 장기 60일 버튼 별 이동평균선 주기 그래프 UI 구현

fix: 이동평균선 주기 버튼 구현

---

src/app/components/MainStockChart.tsx
src/app/page.tsx
src/app/styles/page.module.css

그래프는 만들었는데 정확히 데이터 받아서 조정해야 할 듯.

feat: main-page 그래프 UI 구현

---

src/main/java/com/stockleague/backend/inquiry/controller/InquiryController.java
src/main/java/com/stockleague/backend/inquiry/domain/Inquiry.java
src/main/java/com/stockleague/backend/inquiry/dto/response/InquiryDeleteResponseDto.java
src/main/java/com/stockleague/backend/inquiry/service/InquiryService.java

1. 문의 삭제 기능 구현
2. 문의 DB 수정 ( closed_at 필드명 answered_at 필드명으로 수정 )
3. swagger 수정 ( 404 오류 -> 400 오류로 수정 )

feat: 문의 삭제 기능 구현

---

src/app/components/OrderHistoryItem.tsx
src/app/components/Portfolio.tsx
src/app/user/account/account.css
src/app/user/account/page.tsx

feat: 포트폴리오 그래프 UI 구현

---

src/app/components/Portfolio.tsx
src/app/page.tsx
src/app/styles/page.module.css

feat: 메인페이지 로그인 시 포트폴리오로 전환 UI 구현

---

src/app/components/MoreVert.tsx
src/app/help/inquiry/inquiry.css
src/app/help/inquiry/page.tsx

리스트에서 각 문의 마다 moreVert로 드롭다운으로 구현

feat: 문의 수정, 삭제 버튼 UI 구현

---

src/app/admin/admin.css
src/app/admin/layout.tsx
src/app/admin/page.tsx
src/app/auth/auth.css
src/app/components/AdminHeader.tsx
src/app/components/Sidebar.tsx
src/app/layout.tsx
src/app/styles/components/AdminHeader.module.css
src/app/styles/components/Sidebar.module.css

feat: 관리자페이지 레이아웃 구성

---

.vscode/settings.json
src/app/help/notice/[id]/page.tsx
src/app/help/notice/notice.css
src/app/help/notice/page.tsx
src/lib/api/notice.ts
src/lib/api/noticeDetail.ts
src/lib/api/noticeSearch.ts
stockleagueMySQL.session.sql

(유저)공지사항 목록 조회, 검색, 상세조회 api 연결

feat: 공지사항 페이지 api 연결

---

src/app/auth/callback/page.tsx
src/app/auth/nickname/page.tsx
src/app/auth/success/page.tsx
src/app/auth/terms/page.tsx
src/app/components/Header.tsx
src/context/AuthContext.tsx
src/context/SocialSignupContext.tsx
src/lib/api/auth.ts

fix: 로그인 api 연동 성공

---

src/app/help/inquiry/inquiry.css
src/app/help/inquiry/page.tsx
src/app/stocks/trade/page.tsx

feat: 로그인 api 거래창, 문의페이지 연동

---

src/context/AuthContext.tsx

토큰이 없어도 알아서 로그아웃 처리, 기존 닉네임으로 로그아웃 요청했다면, refreshToken으로 판단하여 로그아웃 요청

fix: 로그아웃 api 수정

---

src/app/components/Comment.tsx
src/app/components/Community.tsx
src/app/components/MainStockChart.tsx
src/app/components/MiniStockList.tsx
src/app/components/StockSelector.tsx
src/app/stocks/layout.tsx
src/app/stocks/trade/page.tsx
src/app/styles/components/Comment.module.css
src/lib/api/comment.ts
src/lib/api/stock.ts

feat: stock, community api 연동

---

src/app/admin/reports/page.tsx
src/app/admin/reports/reports.css
src/app/components/ReportDetailModal.tsx
src/lib/api/comment.ts

신고하기 및 신고 목록, 상세 불러오기 연동
(댓 삭제, 경고, 정지 구현 x)

feat: 어드민 페이지 신고관리 api 연동

---

lwc-plugin-trendline/.gitignore
lwc-plugin-trendline/README.md
lwc-plugin-trendline/compile.mjs
lwc-plugin-trendline/index.html
lwc-plugin-trendline/package.json
lwc-plugin-trendline/src/axis-pane-renderer.ts
lwc-plugin-trendline/src/axis-pane-view.ts
lwc-plugin-trendline/src/axis-view.ts
lwc-plugin-trendline/src/data-source.ts
lwc-plugin-trendline/src/example/example.ts
lwc-plugin-trendline/src/example/index.html
lwc-plugin-trendline/src/helpers/assertions.ts
lwc-plugin-trendline/src/helpers/dimensions/common.ts
lwc-plugin-trendline/src/helpers/dimensions/crosshair-width.ts
lwc-plugin-trendline/src/helpers/dimensions/full-width.ts
lwc-plugin-trendline/src/helpers/dimensions/positions.ts
lwc-plugin-trendline/src/helpers/time.ts
lwc-plugin-trendline/src/options.ts
lwc-plugin-trendline/src/pane-renderer.ts
lwc-plugin-trendline/src/pane-view.ts
lwc-plugin-trendline/src/plugin-base.ts
lwc-plugin-trendline/src/sample-data.ts
lwc-plugin-trendline/src/trendline.ts
lwc-plugin-trendline/src/vite-env.d.ts
lwc-plugin-trendline/src/vite.config.js
lwc-plugin-trendline/tsconfig.json
src/app/components/StockChart.tsx
src/app/styles/components/StockChart.module.css

feat: 차트 안 트렌드라인 그리기 구현 중

---

src/app/components/FilterMenu.tsx
src/app/components/StockChart.tsx
src/app/components/StockSelector.tsx
src/app/components/TimeIntervalSelector.tsx
src/app/stocks/trade/page.tsx
src/lib/api/stock.ts

fix: 종목 선택 필터 로그인 비로그인 구분 및 버그 및 초기로딩 설정

---

src/app/components/StockChart.tsx

아직 자잘한 버그가 있음 주기를 (년) 같이 데이터 양이 적은 차트는 없는 부분을 호출하려다 차트가 깨지는 현상 발생
평균이동선을 눌러주거나 하면 괜찮아지긴 하는데 고쳐야 할 부분

fix: 주가 차트와 거래량 차트 움직임 동기화 & 과거 데이터 추가 로드 구현(무한스크롤)

---

src/app/admin/inquiries/inquiries.css
src/app/admin/inquiries/page.tsx
src/app/components/stock/StockOrder.tsx
src/app/components/utills/MobileMenu.tsx
src/app/components/utills/NotificationMenu.tsx
src/app/help/inquiry/[id]/inquiryDetailPage.css
src/app/help/inquiry/[id]/page.tsx
src/app/help/inquiry/inquiry.css
src/app/help/inquiry/page.tsx
src/app/help/inquiry/write/write.css
src/app/styles/components/utills/Notification.module.css
src/app/styles/page.module.css
src/app/user/account-settings/account-settings.css
src/app/user/account-settings/page.tsx
src/context/NotificationContext.tsx
src/lib/api/auth.ts
src/lib/api/stock.ts

테스트 완료 목록
- 로그인
- 알림
- 랭킹
- 메인
- 공지
- 어드민
- 정보 수정(닉네임)

닉네임 변경 제한 및 오류 처리 추가, 입력창 UI 개선, 일부 테스팅 완료
